// Murphy Industrial Products — catalog data
// Realistic sample data structured to match the printable catalog pages.
// Covers rigging hardware, slings, chain, hooks, wire rope, tie-downs, etc.

window.MURPHY_CATEGORIES = [
  {
    id: 'synthetic-slings',
    name: 'Synthetic & Web Slings',
    blurb: 'Polyester roundslings, web slings, and tow straps. Color-coded by capacity.',
    icon: 'sling',
  },
  {
    id: 'chain',
    name: 'Chain & Chain Accessories',
    blurb: 'Grade 30 through Grade 120 chain, assemblies, and components.',
    icon: 'chain',
  },
  {
    id: 'rigging-hardware',
    name: 'Rigging Hardware',
    blurb: 'Shackles, hooks, turnbuckles, eye bolts, wire rope clips.',
    icon: 'shackle',
  },
  {
    id: 'wire-rope',
    name: 'Wire Rope & Cable',
    blurb: 'Galvanized and stainless wire rope, fittings, and assemblies.',
    icon: 'cable',
  },
  {
    id: 'tie-downs',
    name: 'Tie-Downs & Cargo Control',
    blurb: 'Ratchet straps, winches, cam buckles, binders, and assemblies.',
    icon: 'strap',
  },
  {
    id: 'lashing',
    name: 'Lashing',
    blurb: 'Forged D-rings, tie-down points, and weld-on lashing hardware.',
    icon: 'shackle',
  },
  {
    id: 'lifting-equipment',
    name: 'Lifting Equipment',
    blurb: 'Lever hoists, chain blocks, trolleys, and beam clamps.',
    icon: 'hoist',
  },
  {
    id: 'sling-protection',
    name: 'Sling Protection',
    blurb: 'Edge guards, corner protectors, sleeves, and wear pads.',
    icon: 'guard',
  },
];

window.MURPHY_PRODUCTS = [
  // ────────── SYNTHETIC SLINGS ──────────
  {
    id: 'endless-roundslings',
    refPage: 'ref_roundsling',
    name: 'Endless Roundslings',
    category: 'synthetic-slings',
    subcategory: 'Roundslings',
    page: 18,
    subtitle: 'Polyester · Color Coded by Capacity · Vertical, Choker & Basket Hitches',
    standards: ['ASME B30.9'],
    material: 'Polyester',
    finish: 'Color-Coded Cover',
    wllRange: '2,600 – 90,000 lbs',
    designFactor: '5:1',
    description: 'Continuous loop slings made of load-bearing polyester yarn encased in a protective double-wall cover. Color coding identifies rated capacity at a glance per ASME B30.9. Can be used in vertical, choker, and basket hitch configurations. Flexible design conforms to irregular loads and minimizes load damage.',
    features: [
      'Polyester yarn core with double-wall protective sleeve',
      'Color-coded per ASME B30.9 capacity standard',
      'Vertical, choker, and basket hitch configurations',
      'Flexible — conforms to irregular loads',
      'Lightweight and non-marring',
      'Minimum 5:1 design factor',
    ],
    warnings: [
      'Always protect roundslings from corners, edges, or protrusions. Refer to the Sling Protection section of this catalog to choose the right protection product for your lift.',
    ],
    specHeaders: ['Part #', 'Color', 'Vertical (lbs)', 'Choker (lbs)', 'Basket @ 90° (lbs)', 'Basket @ 45° (lbs)', 'Min Length (ft)', 'Weight (lbs/ft)', 'Body Dia. (in)'],
    specRows: [
      ['ENR1',  'Purple', '2,600',  '2,100',  '5,200',   '3,600',   "3'", '0.30', '0.625'],
      ['ENR2',  'Green',  '5,300',  '4,200',  '10,600',  '7,400',   "3'", '0.40', '0.875'],
      ['ENR3',  'Yellow', '8,400',  '6,700',  '16,800',  '11,800',  "3'", '0.50', '1.125'],
      ['ENR4',  'Tan',    '10,600', '8,500',  '21,200',  '14,000',  "3'", '0.60', '1.125'],
      ['ENR5',  'Red',    '13,200', '10,600', '26,400',  '18,000',  "3'", '0.80', '1.375'],
      ['ENR6',  'White',  '16,800', '13,400', '33,600',  '23,000',  "6'", '0.90', '1.375'],
      ['ENR7',  'Blue',   '21,200', '17,000', '42,400',  '29,000',  "6'", '1.30', '1.625'],
      ['ENR8',  'Orange', '25,000', '20,000', '50,000',  '35,000',  "6'", '1.60', '1.750'],
      ['ENR9',  'Orange', '31,000', '24,800', '62,000',  '43,000',  "6'", '2.00', '2.125'],
      ['ENR10', 'Orange', '40,000', '32,000', '80,000',  '56,000',  "6'", '2.60', '2.350'],
      ['ENR11', 'Orange', '53,000', '42,400', '106,000', '74,000',  "8'", '3.40', '3.150'],
      ['ENR12', 'Orange', '66,000', '52,800', '132,000', '93,000',  "8'", '4.30', '3.950'],
      ['ENR13', 'Orange', '90,000', '72,000', '180,000', '127,000', "8'", '5.90', '4.800'],
    ],
    related: ['eye-eye-web-slings', 'sling-edge-guards', 'shackles-anchor'],
    tags: ['overhead lifting', 'soft sling', 'polyester', 'color coded'],
  },
  {
    id: 'eye-eye-web-slings',
    name: 'Eye & Eye Web Slings',
    category: 'synthetic-slings',
    subcategory: 'Web Slings',
    page: 19,
    subtitle: 'Flat Polyester Web · Flat Eye · EE Type 3 & 4',
    standards: ['ASME B30.9', 'WSTDA-WS-1'],
    material: 'Polyester Web',
    finish: 'Flat Eye',
    wllRange: '1,600 – 36,000 lbs',
    designFactor: '5:1',
    description: 'Flat polyester web slings with reinforced flat eyes at each end. Broad bearing surface distributes the load; soft, flexible construction is easy on finished loads. Available in 1-ply and 2-ply constructions and widths from 1" to 6".',
    features: [
      '100% polyester webbing — low elongation',
      'Reinforced red-core wear indicator',
      'Flat eye reduces abrasion at hook/shackle',
      'Light weight; easy to rig',
      'Color-coded warning label on every sling',
    ],
    warnings: [
      'Inspect before every use. Remove from service if red wear-indicator yarns are visible.',
      'Protect from cuts, corners, and chemical exposure.',
    ],
    specHeaders: ['Part #', 'Width (in)', 'Ply', 'Vertical (lbs)', 'Choker (lbs)', 'Basket (lbs)'],
    specRows: [
      ['EE1-901',  '1',  '1', '1,600',  '1,280',  '3,200'],
      ['EE1-902',  '2',  '1', '3,200',  '2,560',  '6,400'],
      ['EE1-903',  '3',  '1', '4,800',  '3,840',  '9,600'],
      ['EE1-904',  '4',  '1', '6,400',  '5,120',  '12,800'],
      ['EE2-901',  '1',  '2', '3,100',  '2,480',  '6,200'],
      ['EE2-902',  '2',  '2', '6,200',  '4,960',  '12,400'],
      ['EE2-903',  '3',  '2', '9,000',  '7,200',  '18,000'],
      ['EE2-904',  '4',  '2', '12,000', '9,600',  '24,000'],
      ['EE2-906',  '6',  '2', '18,000', '14,400', '36,000'],
    ],
    related: ['endless-roundslings', 'sling-edge-guards'],
    tags: ['overhead lifting', 'flat web', 'polyester'],
  },
  {
    id: 'twisted-eye-web-slings',
    name: 'Twisted Eye Web Slings',
    category: 'synthetic-slings',
    subcategory: 'Web Slings',
    page: 20,
    subtitle: 'Polyester · Twisted Eye · Ideal for Choker Hitches',
    standards: ['ASME B30.9'],
    material: 'Polyester Web',
    finish: 'Twisted Eye',
    wllRange: '1,600 – 24,000 lbs',
    designFactor: '5:1',
    description: 'Polyester web slings with a 90° twisted eye at each end. The twisted eye aligns naturally with a choker hitch, reducing wear at the body-to-eye transition.',
    features: [
      'Twisted eye orients correctly in choker hitch',
      'Polyester webbing with red-core wear indicator',
      '1-ply and 2-ply options',
    ],
    warnings: [
      'Always use sling protection on corners and edges.',
    ],
    specHeaders: ['Part #', 'Width (in)', 'Ply', 'Vertical (lbs)', 'Choker (lbs)', 'Basket (lbs)'],
    specRows: [
      ['TE1-902', '2', '1', '3,200',  '2,560',  '6,400'],
      ['TE1-903', '3', '1', '4,800',  '3,840',  '9,600'],
      ['TE2-902', '2', '2', '6,200',  '4,960',  '12,400'],
      ['TE2-903', '3', '2', '9,000',  '7,200',  '18,000'],
      ['TE2-904', '4', '2', '12,000', '9,600',  '24,000'],
    ],
    related: ['eye-eye-web-slings', 'endless-roundslings'],
    tags: ['choker', 'polyester'],
  },

  // ────────── CHAIN ──────────
  {
    id: 'chain-grade-43',
    refPage: 'ref_chain_g43_g30',
    name: 'High Test Chain',
    grade: 'Grade 43',
    category: 'chain',
    subcategory: 'Transport Chain',
    page: 21,
    subtitle: 'ASTM & NACM · High Test · Transport & Tie-Down',
    standards: ['ASTM A413', 'NACM'],
    material: 'Carbon Steel',
    finish: 'Self Colored, Galvanized',
    wllRange: '2,600 – 20,200 lbs',
    designFactor: '3:1',
    description: 'Grade 43 chain, commonly called High Test, is manufactured to meet ASTM and NACM specifications. Typical uses include container securement, logging, towing, and marine industry. Available in many finishes and package configurations. Not for overhead lifting.',
    features: [
      'Meets ASTM & NACM standards',
      'Self-colored and galvanized finishes',
      '50% stronger than Grade 30 chain',
      'Permanent identification on every link',
      '100% proof tested',
      'Design factor 3:1',
    ],
    warnings: [
      'Do not use for overhead lifting. For overhead lifting, specify Grade 80, 100, or 120 alloy chain.',
    ],
    specHeaders: ['Trade Size (in)', 'WLL (lbs)', 'Material Dia. (in)', 'Inside Length (in)', 'Inside Width (in)', 'Weight (lbs/ft)'],
    specRows: [
      ['1/4',  '2,600',  '0.28', '1.24', '0.38', '0.80'],
      ['5/16', '3,900',  '0.33', '1.30', '0.46', '1.15'],
      ['3/8',  '5,400',  '0.39', '1.38', '0.54', '1.60'],
      ['7/16', '7,200',  '0.45', '1.56', '0.60', '2.13'],
      ['1/2',  '9,200',  '0.51', '1.79', '0.68', '2.85'],
      ['5/8',  '11,500', '0.62', '2.15', '0.83', '4.20'],
      ['3/4',  '15,800', '0.75', '2.56', '0.97', '6.20'],
      ['7/8',  '20,200', '0.88', '2.75', '1.10', '8.25'],
    ],
    related: ['chain-grade-70', 'chain-grade-80', 'clevis-grab-hook'],
    tags: ['transport', 'tie-down', 'carbon'],
  },
  {
    id: 'chain-grade-30',
    name: 'Proof Coil Chain',
    grade: 'Grade 30',
    category: 'chain',
    subcategory: 'Utility Chain',
    page: 21,
    subtitle: 'General Utility · Not for Overhead Lifting',
    standards: ['ASTM A413', 'NACM'],
    material: 'Low Carbon Steel',
    finish: 'Self Colored, Galvanized, Zinc Plated',
    wllRange: '800 – 6,900 lbs',
    designFactor: '4:1',
    description: 'Grade 30 Proof Coil is a general-purpose utility chain used in light-duty applications such as load binding, towing, agricultural, and logging. Made to meet ASTM and NACM specifications.',
    features: [
      'General utility grade',
      'Self-colored, galvanized, or zinc-plated finishes',
      'Meets ASTM & NACM standards',
      '100% proof tested',
      'Design factor 4:1',
    ],
    warnings: [
      'Not for overhead lifting.',
    ],
    specHeaders: ['Trade Size (in)', 'WLL (lbs)', 'Material Dia. (in)', 'Inside Length (in)', 'Weight (lbs/ft)'],
    specRows: [
      ['3/16', '800',   '0.22', '0.98', '0.55'],
      ['1/4',  '1,300', '0.28', '1.24', '0.80'],
      ['5/16', '1,900', '0.33', '1.30', '1.15'],
      ['3/8',  '2,650', '0.39', '1.38', '1.60'],
      ['7/16', '3,700', '0.45', '1.56', '2.13'],
      ['1/2',  '4,500', '0.51', '1.79', '2.85'],
      ['5/8',  '6,900', '0.62', '2.15', '4.20'],
    ],
    related: ['chain-grade-43', 'clevis-slip-hook'],
    tags: ['utility', 'general purpose'],
  },
  {
    id: 'chain-grade-70',
    refPage: 'ref_chain_g70_transport',
    name: 'Transport Chain',
    grade: 'Grade 70',
    category: 'chain',
    subcategory: 'Transport Chain',
    page: 22,
    subtitle: 'Gold Chromate · DOT-Approved Cargo Securement',
    standards: ['NACM', 'DOT/CVSA'],
    material: 'Heat Treated Carbon Steel',
    finish: 'Gold Chromate',
    wllRange: '3,150 – 11,300 lbs',
    designFactor: '4:1',
    description: 'Grade 70 transport chain is the standard for cargo securement under DOT and CVSA regulations. Heat-treated carbon steel with gold chromate finish for durability and easy identification.',
    features: [
      'DOT/CVSA approved for cargo securement',
      'Gold chromate finish for corrosion resistance',
      '20% stronger than Grade 43',
      'Embossed with "7" or "70" on every link',
      '100% proof tested',
    ],
    warnings: [
      'Not for overhead lifting.',
    ],
    specHeaders: ['Trade Size (in)', 'WLL (lbs)', 'Material Dia. (in)', 'Weight (lbs/ft)'],
    specRows: [
      ['1/4',  '3,150',  '0.28', '0.80'],
      ['5/16', '4,700',  '0.33', '1.15'],
      ['3/8',  '6,600',  '0.39', '1.60'],
      ['1/2',  '11,300', '0.51', '2.85'],
    ],
    related: ['chain-grade-43', 'ratchet-load-binder', 'grab-hook-eye'],
    tags: ['transport', 'DOT', 'cargo'],
  },
  {
    id: 'chain-grade-80',
    name: 'Alloy Chain',
    grade: 'Grade 80',
    category: 'chain',
    subcategory: 'Lifting Chain',
    page: 23,
    subtitle: 'Alloy · For Overhead Lifting · ASTM A973',
    standards: ['ASTM A973', 'NACM 96', 'ASME B30.9'],
    material: 'Alloy Steel',
    finish: 'Black Painted',
    wllRange: '3,500 – 47,700 lbs',
    designFactor: '4:1',
    description: 'Grade 80 alloy chain is designed and approved for overhead lifting. Heat-treated alloy steel construction provides the strength and elongation characteristics required for lifting service. Used to build chain slings and lifting assemblies.',
    features: [
      'Approved for overhead lifting',
      'Heat-treated alloy steel',
      'Embossed with "8" or "80" for identification',
      '100% proof tested to 2× WLL',
      'Meets ASTM A973 and ASME B30.9',
    ],
    warnings: [
      'Inspect before every use per ASME B30.9. Remove from service at 10% wear or any deformation.',
    ],
    specHeaders: ['Trade Size (mm)', 'Trade Size (in)', 'WLL (lbs)', 'Weight (lbs/ft)'],
    specRows: [
      ['7',   '9/32', '3,500',  '1.05'],
      ['9',   '3/8',  '7,100',  '1.76'],
      ['10',  '3/8',  '8,800',  '2.21'],
      ['13',  '1/2',  '15,000', '3.68'],
      ['16',  '5/8',  '22,600', '5.60'],
      ['20',  '3/4',  '35,300', '8.82'],
      ['22',  '7/8',  '42,700', '10.67'],
      ['26',  '1',    '47,700', '14.80'],
    ],
    related: ['chain-grade-100', 'alloy-sling-hook', 'chain-slings'],
    tags: ['overhead lifting', 'alloy', 'chain sling'],
  },
  {
    id: 'chain-grade-100',
    refPage: 'ref_chain_herc_g100',
    name: 'Alloy Chain',
    grade: 'Grade 100',
    category: 'chain',
    subcategory: 'Lifting Chain',
    page: 23,
    subtitle: 'Alloy · 25% Stronger than Grade 80 · For Overhead Lifting',
    standards: ['ASTM A973', 'NACM', 'ASME B30.9'],
    material: 'Alloy Steel',
    finish: 'Painted Pink or Black',
    wllRange: '4,300 – 59,700 lbs',
    designFactor: '4:1',
    description: 'Grade 100 alloy chain provides 25% more working load limit than Grade 80 at the same trade size. Ideal where weight reduction matters — chain slings for overhead lifting.',
    features: [
      '25% stronger than Grade 80 at the same size',
      'Approved for overhead lifting',
      'Embossed with "10" or "100"',
      '100% proof tested',
    ],
    warnings: [
      'Use only Grade 100 rated components in Grade 100 assemblies.',
    ],
    specHeaders: ['Trade Size (mm)', 'WLL (lbs)', 'Weight (lbs/ft)'],
    specRows: [
      ['7',  '4,300',  '1.05'],
      ['9',  '8,800',  '1.76'],
      ['10', '11,300', '2.21'],
      ['13', '19,100', '3.68'],
      ['16', '28,000', '5.60'],
      ['20', '44,100', '8.82'],
      ['22', '53,000', '10.67'],
      ['26', '59,700', '14.80'],
    ],
    related: ['chain-grade-80', 'alloy-sling-hook'],
    tags: ['overhead lifting', 'alloy', 'high strength'],
  },

  // ────────── RIGGING HARDWARE ──────────
  {
    id: 'shackles-anchor',
    refPage: 'ref_shackles_cm_super_strong',
    name: 'Anchor Shackles',
    category: 'rigging-hardware',
    subcategory: 'Shackles',
    page: 30,
    subtitle: 'Screw Pin · Bolt Type · Hot Dip Galvanized · Forged',
    standards: ['ASME B30.26', 'Federal Spec RR-C-271'],
    material: 'Forged Carbon Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '0.33 – 55 tons',
    designFactor: '6:1',
    description: 'Forged carbon steel anchor (bow) shackles with screw pin or bolt-type pin. Wide bow accepts multi-leg sling arrangements without pinching. Meets the requirements of ASME B30.26 and Federal Specification RR-C-271.',
    features: [
      'Forged, Quenched & Tempered',
      'Hot dip galvanized steel',
      'Screw pin or bolt, nut & cotter options',
      'Fatigue rated',
      'Permanent identification — size, WLL, trace code',
      'Meets ASME B30.26',
    ],
    warnings: [
      'Never side-load a screw-pin shackle beyond rated angular capacity.',
      'Use bolt-type shackles for long-term or permanent installations.',
    ],
    specHeaders: ['Part #', 'Size (in)', 'WLL (tons)', 'Pin Dia. (in)', 'Inside Width (in)', 'Weight (lbs)'],
    specRows: [
      ['MAS-033', '3/16', '0.33', '0.25',  '0.38', '0.08'],
      ['MAS-050', '1/4',  '0.50', '0.31',  '0.47', '0.15'],
      ['MAS-075', '5/16', '0.75', '0.38',  '0.53', '0.23'],
      ['MAS-100', '3/8',  '1.00', '0.44',  '0.66', '0.36'],
      ['MAS-150', '7/16', '1.50', '0.50',  '0.75', '0.54'],
      ['MAS-200', '1/2',  '2.00', '0.63',  '0.81', '0.79'],
      ['MAS-325', '5/8',  '3.25', '0.75',  '1.06', '1.45'],
      ['MAS-475', '3/4',  '4.75', '0.88',  '1.25', '2.35'],
      ['MAS-650', '7/8',  '6.50', '1.00',  '1.44', '3.60'],
      ['MAS-850', '1',    '8.50', '1.13',  '1.69', '5.10'],
      ['MAS-950', '1-1/8','9.50', '1.25',  '1.81', '7.20'],
      ['MAS-1200','1-1/4','12.00','1.38',  '2.03', '9.10'],
      ['MAS-1350','1-3/8','13.50','1.50',  '2.25', '12.00'],
      ['MAS-1700','1-1/2','17.00','1.63',  '2.38', '15.00'],
      ['MAS-2500','1-3/4','25.00','2.00',  '2.88', '23.50'],
      ['MAS-3500','2',    '35.00','2.25',  '3.25', '32.00'],
      ['MAS-5500','2-1/2','55.00','2.75',  '4.13', '62.50'],
    ],
    related: ['shackles-chain', 'eye-bolts', 'wire-rope-thimbles'],
    tags: ['shackle', 'screw pin', 'bow'],
  },
  {
    id: 'shackles-chain',
    refPage: 'ref_shackle_longreach',
    name: 'Chain Shackles',
    category: 'rigging-hardware',
    subcategory: 'Shackles',
    page: 30,
    subtitle: 'Screw Pin · Bolt Type · Narrow D-Pattern',
    standards: ['ASME B30.26'],
    material: 'Forged Carbon Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '0.33 – 35 tons',
    designFactor: '6:1',
    description: 'Chain (D or dee) shackles have a narrow body ideal for single inline connections. Not recommended for multi-leg sling arrangements — use anchor shackles instead.',
    features: [
      'Forged, Quenched & Tempered',
      'Hot dip galvanized',
      'Permanent ID: size, WLL, trace code',
      'Meets ASME B30.26',
    ],
    warnings: [
      'Chain shackles are for in-line loading only. Use anchor (bow) shackles for multi-leg slings.',
    ],
    specHeaders: ['Part #', 'Size (in)', 'WLL (tons)', 'Pin Dia. (in)', 'Weight (lbs)'],
    specRows: [
      ['MCS-050', '1/4',  '0.50', '0.31', '0.14'],
      ['MCS-100', '3/8',  '1.00', '0.44', '0.34'],
      ['MCS-200', '1/2',  '2.00', '0.63', '0.74'],
      ['MCS-325', '5/8',  '3.25', '0.75', '1.35'],
      ['MCS-475', '3/4',  '4.75', '0.88', '2.20'],
      ['MCS-650', '7/8',  '6.50', '1.00', '3.30'],
      ['MCS-850', '1',    '8.50', '1.13', '4.70'],
      ['MCS-1200','1-1/4','12.00','1.38', '8.40'],
      ['MCS-1700','1-1/2','17.00','1.63', '13.80'],
      ['MCS-2500','1-3/4','25.00','2.00', '21.50'],
      ['MCS-3500','2',    '35.00','2.25', '30.00'],
    ],
    related: ['shackles-anchor', 'clevis-grab-hook'],
    tags: ['shackle', 'chain', 'd-pattern'],
  },
  {
    id: 'jaw-jaw-turnbuckles',
    refPage: 'ref_turnbuckle_2',
    name: 'Jaw & Jaw Turnbuckles',
    category: 'rigging-hardware',
    subcategory: 'Turnbuckles',
    page: 22,
    subtitle: 'Hot Dip Galvanized · Forged · Fatigue Rated · ASME B30.26',
    standards: ['ASME B30.26'],
    material: 'Forged Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '500 – 45,200 lbs',
    designFactor: '5:1',
    description: 'Forged jaw & jaw turnbuckles for straight or in-line pull. End fittings are Quenched & Tempered or Normalized; bodies are heat-treated by normalizing. Modified UNJ thread on end fittings for improved fatigue performance.',
    features: [
      'End fittings Q&T or normalized; bodies normalized',
      'Hot dip galvanized steel',
      'Recommended for straight or in-line pull only',
      'Forged jaw ends: bolt/nut 1/4" – 5/8"; pin/cotter 3/4" – 2-3/4"',
      'Modified UNJ thread for improved fatigue',
      'UNC body thread · Lock nuts available',
      'Fatigue Rated · Meets or exceeds ASME B30.26',
    ],
    warnings: [
      'For straight or in-line pull only.',
      'Sizes 1/4" – 5/8" ship with bolts and nuts; 3/4" and larger ship with pin and cotter only.',
    ],
    specHeaders: ['Part #', 'Size × Take-Up (in)', 'WLL (lbs)', 'Jaw ID (in)', 'Pin Dia. (in)', 'Weight (lbs)'],
    specRows: [
      ['TB-JJ-14-04', '1/4 × 4',    '500',    '0.31', '0.31', '0.40'],
      ['TB-JJ-38-06', '3/8 × 6',    '1,200',  '0.44', '0.44', '1.10'],
      ['TB-JJ-12-06', '1/2 × 6',    '2,200',  '0.53', '0.53', '1.90'],
      ['TB-JJ-12-09', '1/2 × 9',    '2,200',  '0.53', '0.53', '2.30'],
      ['TB-JJ-12-12', '1/2 × 12',   '2,200',  '0.53', '0.53', '2.80'],
      ['TB-JJ-58-06', '5/8 × 6',    '3,500',  '0.63', '0.63', '3.40'],
      ['TB-JJ-58-09', '5/8 × 9',    '3,500',  '0.63', '0.63', '4.10'],
      ['TB-JJ-58-12', '5/8 × 12',   '3,500',  '0.63', '0.63', '4.80'],
      ['TB-JJ-34-06', '3/4 × 6',    '5,200',  '0.75', '0.75', '5.60'],
      ['TB-JJ-34-09', '3/4 × 9',    '5,200',  '0.75', '0.75', '6.40'],
      ['TB-JJ-34-12', '3/4 × 12',   '5,200',  '0.75', '0.75', '7.30'],
      ['TB-JJ-78-12', '7/8 × 12',   '7,200',  '0.88', '0.88', '10.50'],
      ['TB-JJ-1-06',  '1 × 6',      '10,000', '1.00', '1.00', '13.80'],
      ['TB-JJ-1-12',  '1 × 12',     '10,000', '1.00', '1.00', '16.50'],
      ['TB-JJ-1-18',  '1 × 18',     '10,000', '1.00', '1.00', '19.80'],
      ['TB-JJ-114-12','1-1/4 × 12', '15,200', '1.13', '1.13', '26.50'],
      ['TB-JJ-12-18', '1-1/2 × 18', '21,400', '1.38', '1.38', '44.00'],
      ['TB-JJ-134-18','1-3/4 × 18', '28,000', '1.63', '1.63', '67.00'],
      ['TB-JJ-2-24',  '2 × 24',     '37,000', '1.88', '1.88', '105.00'],
      ['TB-JJ-234-24','2-3/4 × 24', '45,200', '2.25', '2.25', '178.00'],
    ],
    related: ['jaw-eye-turnbuckles', 'eye-eye-turnbuckles', 'shackles-anchor'],
    tags: ['turnbuckle', 'tensioner', 'jaw'],
  },
  {
    id: 'jaw-eye-turnbuckles',
    refPage: 'ref_turnbuckle_jaw_eye',
    name: 'Jaw & Eye Turnbuckles',
    category: 'rigging-hardware',
    subcategory: 'Turnbuckles',
    page: 22,
    subtitle: 'Hot Dip Galvanized · Forged · ASME B30.26',
    standards: ['ASME B30.26'],
    material: 'Forged Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '500 – 45,200 lbs',
    designFactor: '5:1',
    description: 'Forged jaw & eye turnbuckles — combine a jaw end for direct pin connection with an eye for use with shackles, slings, or hooks.',
    features: [
      'Q&T or normalized end fittings',
      'Hot dip galvanized',
      'Modified UNJ thread on end fittings',
      'UNC body thread',
      'Meets ASME B30.26',
    ],
    warnings: [
      'For straight or in-line pull only.',
    ],
    specHeaders: ['Part #', 'Size × Take-Up (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['TB-JE-38-06', '3/8 × 6',  '1,200',  '1.00'],
      ['TB-JE-12-09', '1/2 × 9',  '2,200',  '2.20'],
      ['TB-JE-58-09', '5/8 × 9',  '3,500',  '3.90'],
      ['TB-JE-34-12', '3/4 × 12', '5,200',  '7.00'],
      ['TB-JE-1-12',  '1 × 12',   '10,000', '16.00'],
      ['TB-JE-114-12','1-1/4 × 12','15,200','26.00'],
    ],
    related: ['jaw-jaw-turnbuckles', 'eye-eye-turnbuckles'],
    tags: ['turnbuckle', 'jaw', 'eye'],
  },
  {
    id: 'eye-eye-turnbuckles',
    refPage: 'ref_turnbuckle_eye_eye',
    name: 'Eye & Eye Turnbuckles',
    category: 'rigging-hardware',
    subcategory: 'Turnbuckles',
    page: 22,
    subtitle: 'Hot Dip Galvanized · Forged · ASME B30.26',
    standards: ['ASME B30.26'],
    material: 'Forged Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '400 – 21,400 lbs',
    designFactor: '5:1',
    description: 'Forged eye & eye turnbuckles — eyes on both ends for connection via shackles, thimbles, or hooks.',
    features: [
      'Q&T or normalized fittings',
      'Hot dip galvanized',
      'UNJ thread end fittings · UNC body thread',
      'Meets ASME B30.26',
    ],
    warnings: [
      'For straight or in-line pull only.',
    ],
    specHeaders: ['Part #', 'Size × Take-Up (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['TB-EE-14-04', '1/4 × 4',   '400',    '0.30'],
      ['TB-EE-38-06', '3/8 × 6',   '1,000',  '0.90'],
      ['TB-EE-12-09', '1/2 × 9',   '2,200',  '2.10'],
      ['TB-EE-58-09', '5/8 × 9',   '3,500',  '3.70'],
      ['TB-EE-34-12', '3/4 × 12',  '5,200',  '6.70'],
      ['TB-EE-1-12',  '1 × 12',    '10,000', '15.30'],
      ['TB-EE-12-18', '1-1/2 × 18','21,400', '42.00'],
    ],
    related: ['jaw-jaw-turnbuckles', 'jaw-eye-turnbuckles'],
    tags: ['turnbuckle', 'eye'],
  },
  {
    id: 'clevis-grab-hook',
    name: 'Clevis Grab Hook',
    category: 'rigging-hardware',
    subcategory: 'Hooks',
    page: 26,
    subtitle: 'Grade 70 · Shortening or End Fitting',
    standards: ['NACM'],
    material: 'Heat Treated Steel',
    finish: 'Gold Chromate',
    wllRange: '2,600 – 11,300 lbs',
    designFactor: '4:1',
    description: 'Clevis grab hooks attach directly to Grade 70 chain without additional hardware. Used to shorten chain or as a fixed end fitting for cargo securement.',
    features: [
      'Matches Grade 70 transport chain',
      'Gold chromate finish',
      'Forged and heat treated',
      'Embossed with size and WLL',
    ],
    warnings: [
      'Not for overhead lifting. Do not side-load grab hooks.',
    ],
    specHeaders: ['Part #', 'Chain Size (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['CGH-14', '1/4',  '2,600',  '0.55'],
      ['CGH-56', '5/16', '3,900',  '0.80'],
      ['CGH-38', '3/8',  '5,400',  '1.10'],
      ['CGH-12', '1/2',  '9,200',  '2.30'],
      ['CGH-58', '5/8',  '11,300', '3.80'],
    ],
    related: ['clevis-slip-hook', 'chain-grade-70', 'ratchet-load-binder'],
    tags: ['hook', 'grab', 'grade 70'],
  },
  {
    id: 'clevis-slip-hook',
    name: 'Clevis Slip Hook',
    category: 'rigging-hardware',
    subcategory: 'Hooks',
    page: 26,
    subtitle: 'Grade 70 · With or Without Latch',
    standards: ['NACM'],
    material: 'Heat Treated Steel',
    finish: 'Gold Chromate',
    wllRange: '2,600 – 11,300 lbs',
    designFactor: '4:1',
    description: 'Clevis slip hooks attach directly to chain and allow the chain to slide through for adjustable connections. Available with or without spring latch.',
    features: [
      'Gold chromate finish',
      'Forged and heat treated',
      'Latch kits available separately',
    ],
    warnings: [
      'Not for overhead lifting.',
    ],
    specHeaders: ['Part #', 'Chain Size (in)', 'WLL (lbs)', 'With Latch'],
    specRows: [
      ['CSH-14', '1/4',  '2,600',  'Yes'],
      ['CSH-56', '5/16', '3,900',  'Yes'],
      ['CSH-38', '3/8',  '5,400',  'Yes'],
      ['CSH-12', '1/2',  '9,200',  'Yes'],
      ['CSH-58', '5/8',  '11,300', 'Yes'],
    ],
    related: ['clevis-grab-hook', 'chain-grade-70'],
    tags: ['hook', 'slip', 'latch'],
  },
  {
    id: 'alloy-sling-hook',
    name: 'Alloy Sling Hook with Latch',
    category: 'rigging-hardware',
    subcategory: 'Hooks',
    page: 27,
    subtitle: 'Grade 80/100 · For Overhead Lifting',
    standards: ['ASME B30.10', 'ASTM A952'],
    material: 'Alloy Steel',
    finish: 'Painted',
    wllRange: '3,500 – 47,700 lbs',
    designFactor: '5:1',
    description: 'Alloy sling hooks with spring-loaded safety latch — approved for overhead lifting when matched to rated Grade 80 or 100 chain slings.',
    features: [
      'Approved for overhead lifting',
      'Spring-loaded safety latch',
      'Heat-treated alloy steel',
      'Permanent ID: size, WLL, trace code',
    ],
    warnings: [
      'Never overload. Remove from service if latch is missing, damaged, or inoperative.',
    ],
    specHeaders: ['Part #', 'Chain Size (mm)', 'Grade', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['ASH-7-80',  '7',  '80',  '3,500',  '0.95'],
      ['ASH-10-80', '10', '80',  '8,800',  '2.70'],
      ['ASH-13-80', '13', '80',  '15,000', '4.80'],
      ['ASH-16-80', '16', '80',  '22,600', '8.20'],
      ['ASH-20-80', '20', '80',  '35,300', '14.00'],
      ['ASH-10-100','10', '100', '11,300', '2.70'],
      ['ASH-13-100','13', '100', '19,100', '4.80'],
      ['ASH-16-100','16', '100', '28,000', '8.20'],
    ],
    related: ['chain-grade-80', 'chain-grade-100'],
    tags: ['hook', 'overhead lifting', 'latch'],
  },
  {
    id: 'eye-bolts',
    name: 'Shoulder Eye Bolts',
    category: 'rigging-hardware',
    subcategory: 'Eye Bolts',
    page: 28,
    subtitle: 'Forged · Drop Forged · Shoulder Pattern',
    standards: ['ASME B18.15'],
    material: 'Forged Carbon Steel',
    finish: 'Self Colored or Galvanized',
    wllRange: '650 – 52,000 lbs',
    designFactor: '5:1',
    description: 'Drop-forged shoulder eye bolts — the shoulder provides bearing surface for angular loading up to 45° off vertical (with reduced WLL). Use non-shoulder (straight) eye bolts for vertical lifts only.',
    features: [
      'Drop forged carbon steel',
      'Shoulder pattern for angular loading',
      'UNC thread',
      'Available plain or hot dip galvanized',
    ],
    warnings: [
      'Reduce WLL for angular loads: 45° loading reduces WLL to approximately 30% of rated.',
      'Always seat the shoulder fully against the bearing surface.',
    ],
    specHeaders: ['Part #', 'Thread × Shank (in)', 'WLL Vertical (lbs)', 'WLL @ 45° (lbs)', 'Weight (lbs)'],
    specRows: [
      ['SEB-14', '1/4 × 1',     '650',    '200',    '0.08'],
      ['SEB-38', '3/8 × 1-1/4', '1,550',  '465',    '0.18'],
      ['SEB-12', '1/2 × 1-3/4', '2,600',  '780',    '0.38'],
      ['SEB-58', '5/8 × 2',     '5,200',  '1,560',  '0.65'],
      ['SEB-34', '3/4 × 2-1/4', '7,200',  '2,160',  '1.05'],
      ['SEB-78', '7/8 × 2-1/2', '10,600', '3,180',  '1.60'],
      ['SEB-1',  '1 × 3',       '13,200', '3,960',  '2.45'],
      ['SEB-114','1-1/4 × 3-1/2','21,000', '6,300',  '4.70'],
      ['SEB-112','1-1/2 × 4',   '31,000', '9,300',  '8.00'],
      ['SEB-2',  '2 × 6',       '52,000', '15,600', '23.00'],
    ],
    related: ['shackles-anchor', 'swivel-hoist-rings'],
    tags: ['eye bolt', 'shoulder'],
  },
  {
    id: 'swivel-hoist-rings',
    name: 'Swivel Hoist Rings',
    category: 'rigging-hardware',
    subcategory: 'Hoist Rings',
    page: 29,
    subtitle: 'Full 360° Swivel · 180° Pivot · Rated for Angular Loading',
    standards: ['ASME B30.26'],
    material: 'Alloy Steel',
    finish: 'Painted Yellow',
    wllRange: '550 – 100,000 lbs',
    designFactor: '5:1',
    description: 'Swivel hoist rings solve the angular loading problem of eye bolts. Bail rotates 180° and body swivels 360° under load — maintains full WLL at any angle.',
    features: [
      'Full 360° swivel, 180° pivot',
      'Full rated capacity at any sling angle',
      'Individually proof-tested to 2× WLL',
      'Serialized and traceable',
    ],
    warnings: [
      'Torque mounting bolt to manufacturer spec before use.',
      'Inspect annually per ASME B30.26.',
    ],
    specHeaders: ['Part #', 'Thread (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['SHR-550',   '1/4-20',   '550',    '0.40'],
      ['SHR-1000',  '3/8-16',   '1,000',  '0.70'],
      ['SHR-2500',  '1/2-13',   '2,500',  '1.20'],
      ['SHR-4000',  '5/8-11',   '4,000',  '2.20'],
      ['SHR-7000',  '3/4-10',   '7,000',  '3.80'],
      ['SHR-10000', '7/8-9',    '10,000', '5.90'],
      ['SHR-15000', '1-8',      '15,000', '8.50'],
      ['SHR-24000', '1-1/4-7',  '24,000', '15.80'],
      ['SHR-30000', '1-1/2-6',  '30,000', '21.00'],
      ['SHR-50000', '1-3/4-5',  '50,000', '37.00'],
      ['SHR-100000','2-1/2-4',  '100,000','95.00'],
    ],
    related: ['eye-bolts', 'shackles-anchor'],
    tags: ['hoist ring', 'swivel', 'angular'],
  },
  {
    id: 'wire-rope-clips',
    name: 'Forged Wire Rope Clips',
    category: 'rigging-hardware',
    subcategory: 'Wire Rope Fittings',
    page: 35,
    subtitle: 'Forged U-Bolt · Hot Dip Galvanized · Federal Spec FF-C-450D',
    standards: ['Federal Spec FF-C-450D Type I Class 1'],
    material: 'Forged Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: 'N/A — efficiency rated',
    designFactor: '—',
    description: 'Forged wire rope clips (U-bolt style) for making eye terminations in wire rope. When installed per Federal Spec FF-C-450D, a properly made termination develops 80% of rope breaking strength.',
    features: [
      'Forged saddle and U-bolt',
      'Hot dip galvanized',
      'Meets FF-C-450D Type I Class 1',
      '"Never saddle a dead horse" — saddle on live side',
    ],
    warnings: [
      'Always install clips with the saddle on the live (load) side of the rope.',
      'Retighten clips after initial loading and again after the rope has seated.',
    ],
    specHeaders: ['Rope Size (in)', 'Min # Clips', 'Torque (ft-lbs)', 'Rope Turn-Back (in)'],
    specRows: [
      ['1/8',  '2', '4.5', '3-1/4'],
      ['3/16', '2', '7.5', '3-3/4'],
      ['1/4',  '2', '15',  '4-3/4'],
      ['5/16', '2', '30',  '5-1/4'],
      ['3/8',  '2', '45',  '6-1/2'],
      ['1/2',  '3', '65',  '11-1/2'],
      ['5/8',  '3', '95',  '12'],
      ['3/4',  '4', '130', '18'],
      ['7/8',  '4', '225', '19'],
      ['1',    '5', '225', '26'],
      ['1-1/8','6', '225', '34'],
      ['1-1/4','7', '360', '44'],
    ],
    related: ['wire-rope-thimbles', 'wire-rope-iwrc'],
    tags: ['wire rope', 'clip', 'u-bolt'],
  },
  {
    id: 'wire-rope-thimbles',
    name: 'Heavy Duty Wire Rope Thimbles',
    category: 'rigging-hardware',
    subcategory: 'Wire Rope Fittings',
    page: 35,
    subtitle: 'Heavy Duty Pattern · Hot Dip Galvanized',
    standards: ['Federal Spec FF-T-276'],
    material: 'Forged Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: 'N/A',
    description: 'Heavy-duty thimbles preserve the eye shape of wire rope terminations and prevent rope-on-hardware wear.',
    features: [
      'Heavy duty forged steel pattern',
      'Hot dip galvanized',
      'Meets Federal Spec FF-T-276',
    ],
    warnings: [],
    specHeaders: ['Rope Size (in)', 'Part #', 'Length (in)', 'Weight (lbs)'],
    specRows: [
      ['1/4',  'HDT-14', '1.75', '0.09'],
      ['3/8',  'HDT-38', '2.50', '0.21'],
      ['1/2',  'HDT-12', '3.25', '0.42'],
      ['5/8',  'HDT-58', '4.00', '0.70'],
      ['3/4',  'HDT-34', '4.75', '1.10'],
      ['1',    'HDT-1',  '6.00', '2.40'],
      ['1-1/4','HDT-114','7.50', '4.20'],
    ],
    related: ['wire-rope-clips', 'wire-rope-iwrc'],
    tags: ['thimble', 'wire rope'],
  },

  // ────────── WIRE ROPE ──────────
  {
    id: 'wire-rope-iwrc',
    name: 'Wire Rope 6×26 IWRC',
    category: 'wire-rope',
    subcategory: 'Wire Rope',
    page: 40,
    subtitle: 'EIPS · IWRC · Regular Lay · Bright Finish',
    standards: ['Federal Spec RR-W-410'],
    material: 'Extra Improved Plow Steel',
    finish: 'Bright (Uncoated)',
    wllRange: '600 – 38,000 lbs (single part, 5:1)',
    designFactor: '5:1',
    description: '6×26 IWRC Warrington-Seale construction wire rope — a balance of flexibility and abrasion resistance. Independent Wire Rope Core adds strength and crushing resistance.',
    features: [
      '6 strands × 26 wires, IWRC',
      'Extra Improved Plow Steel (EIPS)',
      'Right regular lay',
      'Rotation-resistant alternate constructions available',
    ],
    warnings: [
      'Inspect for broken wires, kinks, birdcaging, and corrosion per ASME B30.9/B30.30.',
    ],
    specHeaders: ['Rope Dia. (in)', 'Weight (lbs/ft)', 'Min Breaking Force (lbs)', 'WLL @ 5:1 (lbs)'],
    specRows: [
      ['1/4',  '0.116', '6,000',   '1,200'],
      ['5/16', '0.180', '9,200',   '1,840'],
      ['3/8',  '0.260', '13,100',  '2,620'],
      ['7/16', '0.350', '17,800',  '3,560'],
      ['1/2',  '0.460', '23,000',  '4,600'],
      ['9/16', '0.590', '29,000',  '5,800'],
      ['5/8',  '0.720', '36,000',  '7,200'],
      ['3/4',  '1.040', '51,200',  '10,240'],
      ['7/8',  '1.420', '69,200',  '13,840'],
      ['1',    '1.850', '89,800',  '17,960'],
      ['1-1/8','2.340', '113,000', '22,600'],
      ['1-1/4','2.890', '138,800', '27,760'],
      ['1-3/8','3.500', '167,000', '33,400'],
      ['1-1/2','4.160', '192,000', '38,400'],
    ],
    related: ['wire-rope-clips', 'wire-rope-thimbles'],
    tags: ['wire rope', '6x26', 'IWRC', 'EIPS'],
  },
  {
    id: 'wire-rope-stainless',
    name: 'Wire Rope 7×19 Stainless',
    category: 'wire-rope',
    subcategory: 'Wire Rope',
    page: 41,
    subtitle: 'T-316 Stainless · 7×19 · Marine Grade',
    standards: ['Mil-DTL-83420'],
    material: 'T-316 Stainless Steel',
    finish: 'Bright Stainless',
    wllRange: '96 – 9,200 lbs (breaking strength shown)',
    description: '7×19 T-316 stainless wire rope — corrosion-resistant for marine, architectural, and food-grade applications. Flexible enough for sheaves and fittings.',
    features: [
      'T-316 stainless — excellent corrosion resistance',
      '7 strands × 19 wires',
      'Marine, architectural, cable railing applications',
    ],
    warnings: [],
    specHeaders: ['Rope Dia. (in)', 'Weight (lbs/ft)', 'Min Breaking Force (lbs)'],
    specRows: [
      ['1/16', '0.008', '480'],
      ['3/32', '0.018', '1,000'],
      ['1/8',  '0.029', '1,760'],
      ['5/32', '0.045', '2,400'],
      ['3/16', '0.065', '3,700'],
      ['1/4',  '0.116', '6,400'],
      ['5/16', '0.180', '9,800'],
      ['3/8',  '0.260', '14,400'],
    ],
    related: ['wire-rope-iwrc'],
    tags: ['stainless', 'marine', '7x19'],
  },

  // ────────── TIE-DOWNS ──────────
  {
    id: 'ratchet-strap-2in',
    refPage: 'ref_ratchet_2in_flat_hooks',
    name: '2" Ratchet Strap Assemblies',
    category: 'tie-downs',
    subcategory: 'Ratchet Straps',
    page: 50,
    subtitle: 'DOT Compliant · Wire Hook, Flat Hook, Chain Anchor Ends',
    standards: ['WSTDA-T-1', 'DOT/CVSA'],
    material: 'Polyester Web + Forged Hardware',
    finish: 'Yellow / Gold',
    wllRange: '3,333 lbs WLL (10,000 lbs break)',
    designFactor: '3:1',
    description: '2" wide polyester ratchet strap assemblies for cargo tie-down. DOT compliant for commercial hauling. Multiple end-fitting options for flatbed, step deck, and trailer applications.',
    features: [
      'Polyester webbing — low stretch',
      'Ergonomic long-handle ratchet',
      'Available end fittings: wire hook, flat hook, chain anchor, double-J',
      'DOT-compliant labeling',
      'WLL 3,333 lbs · Break 10,000 lbs',
    ],
    warnings: [
      'Inspect before every use. Remove from service if webbing is cut, faded, burned, or ratchet is damaged.',
    ],
    specHeaders: ['Part #', 'Length (ft)', 'End Fitting', 'WLL (lbs)', 'Break (lbs)'],
    specRows: [
      ['RS2-27-WH', '27', 'Wire Hook',    '3,333', '10,000'],
      ['RS2-27-FH', '27', 'Flat Hook',    '3,333', '10,000'],
      ['RS2-27-CE', '27', 'Chain Anchor', '3,333', '10,000'],
      ['RS2-30-WH', '30', 'Wire Hook',    '3,333', '10,000'],
      ['RS2-30-FH', '30', 'Flat Hook',    '3,333', '10,000'],
      ['RS2-40-FH', '40', 'Flat Hook',    '3,333', '10,000'],
    ],
    related: ['ratchet-strap-4in', 'ratchet-load-binder'],
    tags: ['tie-down', 'ratchet', 'cargo'],
  },
  {
    id: 'ratchet-strap-4in',
    name: '4" Ratchet Strap Assemblies',
    category: 'tie-downs',
    subcategory: 'Ratchet Straps',
    page: 50,
    subtitle: 'Heavy Duty · Flatbed · Flat Hook or Chain Anchor',
    standards: ['WSTDA-T-1', 'DOT/CVSA'],
    material: 'Polyester Web + Forged Hardware',
    finish: 'Yellow',
    wllRange: '5,400 lbs WLL (16,200 lbs break)',
    designFactor: '3:1',
    description: '4" heavy-duty ratchet straps for flatbed and heavy cargo applications.',
    features: [
      '4" polyester webbing',
      'Heavy-duty long-handle ratchet',
      'WLL 5,400 lbs · Break 16,200 lbs',
      'DOT compliant',
    ],
    warnings: [
      'Inspect before every use.',
    ],
    specHeaders: ['Part #', 'Length (ft)', 'End Fitting', 'WLL (lbs)', 'Break (lbs)'],
    specRows: [
      ['RS4-27-FH', '27', 'Flat Hook',    '5,400', '16,200'],
      ['RS4-30-FH', '30', 'Flat Hook',    '5,400', '16,200'],
      ['RS4-30-CE', '30', 'Chain Anchor', '5,400', '16,200'],
      ['RS4-40-FH', '40', 'Flat Hook',    '5,400', '16,200'],
    ],
    related: ['ratchet-strap-2in', 'ratchet-load-binder'],
    tags: ['tie-down', 'ratchet', 'flatbed'],
  },
  {
    id: 'ratchet-load-binder',
    name: 'Ratchet Load Binder',
    category: 'tie-downs',
    subcategory: 'Load Binders',
    page: 52,
    subtitle: 'Grade 70 / 80 Compatible · Drop-Forged',
    standards: ['NACM', 'DOT/CVSA'],
    material: 'Drop Forged Alloy Steel',
    finish: 'Yellow Chromate or Red Paint',
    wllRange: '5,400 – 13,000 lbs',
    designFactor: '3:1',
    description: 'Ratchet-style load binder for tensioning chain in cargo securement. Safer and easier to use than lever binders — no stored energy release.',
    features: [
      'Drop forged handles and hooks',
      'Low-profile ratchet mechanism',
      'Matches Grade 70 and Grade 80 chain',
      'Handle extension tubes available',
    ],
    warnings: [
      'Never use a cheater bar on ratchet binders.',
    ],
    specHeaders: ['Part #', 'Chain Size G70 (in)', 'Chain Size G80 (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['RLB-38', '3/8',       '5/16',       '6,600',  '8.0'],
      ['RLB-12', '1/2',       '3/8',        '9,200',  '12.5'],
      ['RLB-58', '5/8',       '1/2',        '13,000', '18.5'],
    ],
    related: ['chain-grade-70', 'chain-grade-80', 'lever-load-binder'],
    tags: ['binder', 'cargo', 'ratchet'],
  },
  {
    id: 'lever-load-binder',
    name: 'Lever Load Binder',
    category: 'tie-downs',
    subcategory: 'Load Binders',
    page: 52,
    subtitle: 'Drop-Forged · Over-Center Lever',
    standards: ['NACM'],
    material: 'Drop Forged Alloy Steel',
    finish: 'Red Paint',
    wllRange: '5,400 – 13,000 lbs',
    designFactor: '3:1',
    description: 'Traditional over-center lever load binder. Compact and fast to operate — familiar to experienced drivers.',
    features: [
      'Drop forged handles and hooks',
      'Over-center locking action',
    ],
    warnings: [
      'Lever binders store energy when tensioned. Release carefully — the handle can swing violently.',
      'Never use a cheater bar.',
    ],
    specHeaders: ['Part #', 'Chain Size G70 (in)', 'WLL (lbs)', 'Weight (lbs)'],
    specRows: [
      ['LLB-38', '3/8', '6,600',  '6.5'],
      ['LLB-12', '1/2', '9,200',  '10.0'],
      ['LLB-58', '5/8', '13,000', '15.0'],
    ],
    related: ['ratchet-load-binder', 'chain-grade-70'],
    tags: ['binder', 'lever', 'cargo'],
  },

  {
    id: 'forged-d-ring-strap',
    refPage: 'ref_d_ring_strap',
    name: 'Forged D-Ring with Strap',
    category: 'lashing',
    subcategory: 'D-Rings',
    page: 53,
    subtitle: 'Type A (Self Colored) & Type B (Galvanized, Offshore) · For Tie-Down Only',
    standards: [],
    material: 'Forged Carbon Steel',
    finish: 'Self Colored or Hot Dip Galvanized',
    wllRange: '7 – 50 Metric Tons BS (Type B)',
    description: 'Forged carbon steel D-rings with weld-on strap for permanent tie-down points. The D-ring pivots 180° to accommodate any load direction. Type A is self-colored for general use; Type B is hot-dip galvanized for offshore and marine applications. Sold as a complete ring and strap set. For tie-down only — do not use for overhead lifting.',
    features: [
      'Forged carbon steel construction',
      'D-Ring pivots 180° to accommodate any load',
      'Weld-on bracket for permanent installation',
      'Type A: Self colored for general use',
      'Type B: Galvanized for offshore/marine',
      'Sold as complete ring & strap set',
    ],
    warnings: [
      'Do not use for overhead lifting. D-Rings are designed for tie-down purposes only.',
      'D-Rings and straps should not be used at temperatures exceeding 500°F.',
    ],
    related: ['ratchet-strap-2in', 'ratchet-strap-4in', 'ratchet-load-binder'],
    tags: ['d-ring', 'tie-down', 'weld-on', 'cargo control'],
  },

  // ────────── LIFTING EQUIPMENT ──────────
  {
    id: 'lever-hoist',
    name: 'Lever Chain Hoist',
    category: 'lifting-equipment',
    subcategory: 'Hoists',
    page: 60,
    subtitle: 'Ratchet Lever · Grade 80 Load Chain · ASME B30.21',
    standards: ['ASME B30.21'],
    material: 'Forged Steel Body · Grade 80 Chain',
    finish: 'Painted',
    wllRange: '0.75 – 9 tons',
    designFactor: '5:1',
    description: 'Lever-operated ratchet chain hoist for pulling, lifting, and tensioning in any orientation. Grade 80 load chain. Free-chain function for rapid positioning.',
    features: [
      'Weston-style self-activating brake',
      'Grade 80 nickel-plated load chain',
      'Free-chain selector',
      '360° rotating top and bottom hooks with latches',
      'Meets ASME B30.21',
    ],
    warnings: [
      'Do not exceed rated capacity. Do not use handle extension.',
    ],
    specHeaders: ['Part #', 'Capacity (tons)', 'Standard Lift (ft)', 'Handle Pull (lbs)', 'Weight (lbs)'],
    specRows: [
      ['LH-075', '0.75', '5',  '57', '15'],
      ['LH-150', '1.5',  '5',  '66', '22'],
      ['LH-300', '3',    '5',  '79', '36'],
      ['LH-600', '6',    '5',  '88', '70'],
      ['LH-900', '9',    '5',  '99', '120'],
    ],
    related: ['chain-block', 'beam-clamp'],
    tags: ['hoist', 'lever', 'come-along'],
  },
  {
    id: 'chain-block',
    name: 'Chain Block Hoist',
    category: 'lifting-equipment',
    subcategory: 'Hoists',
    page: 60,
    subtitle: 'Hand Chain · Grade 80 Load Chain · ASME B30.16',
    standards: ['ASME B30.16'],
    material: 'Forged Steel · Grade 80 Chain',
    finish: 'Painted',
    wllRange: '0.5 – 20 tons',
    designFactor: '5:1',
    description: 'Hand-chain block hoist for vertical overhead lifting. Hardened steel gears; Grade 80 load chain.',
    features: [
      'Grade 80 load chain, 100% tested',
      'Hardened alloy gears',
      'Weston brake with double-pawl',
      'Rotating hooks with latches',
    ],
    warnings: [
      'Inspect daily per ASME B30.16.',
    ],
    specHeaders: ['Part #', 'Capacity (tons)', 'Standard Lift (ft)', 'Weight (lbs)'],
    specRows: [
      ['CB-050', '0.5', '10', '22'],
      ['CB-100', '1',   '10', '27'],
      ['CB-200', '2',   '10', '44'],
      ['CB-300', '3',   '10', '66'],
      ['CB-500', '5',   '10', '110'],
      ['CB-1000','10',  '10', '198'],
      ['CB-2000','20',  '10', '420'],
    ],
    related: ['lever-hoist', 'beam-clamp', 'trolley'],
    tags: ['hoist', 'chain block', 'overhead'],
  },
  {
    id: 'beam-clamp',
    name: 'Adjustable Beam Clamp',
    category: 'lifting-equipment',
    subcategory: 'Beam Clamps',
    page: 62,
    subtitle: 'Screw Adjustable · Fits Wide Range of Beams',
    standards: ['ASME B30.20'],
    material: 'Steel',
    finish: 'Painted Yellow',
    wllRange: '1 – 10 tons',
    designFactor: '5:1',
    description: 'Screw-adjustable beam clamps provide a rated attachment point on I-beams for temporary hoist mounting.',
    features: [
      'Adjustable jaw fits a wide range of beam flanges',
      'Integrated shackle eye',
      'Meets ASME B30.20',
    ],
    warnings: [
      'Verify full-flange engagement before applying load.',
    ],
    specHeaders: ['Part #', 'Capacity (tons)', 'Beam Flange Range (in)', 'Weight (lbs)'],
    specRows: [
      ['BC-100',  '1',  '3 – 9',   '11'],
      ['BC-200',  '2',  '3 – 12',  '18'],
      ['BC-300',  '3',  '3 – 12',  '26'],
      ['BC-500',  '5',  '4 – 14',  '44'],
      ['BC-1000', '10', '5 – 16',  '77'],
    ],
    related: ['chain-block', 'trolley'],
    tags: ['beam clamp', 'overhead'],
  },
  {
    id: 'trolley',
    name: 'Push Beam Trolley',
    category: 'lifting-equipment',
    subcategory: 'Trolleys',
    page: 62,
    subtitle: 'Adjustable · I-Beam Push Trolley',
    standards: ['ASME B30.17'],
    material: 'Steel',
    finish: 'Painted',
    wllRange: '1 – 10 tons',
    designFactor: '5:1',
    description: 'Plain (push) trolley for mounting chain hoists to overhead I-beams. Adjustable for a wide range of flange widths.',
    features: [
      'Adjustable flange width',
      'Forged steel wheels',
      'Meets ASME B30.17',
    ],
    warnings: [],
    specHeaders: ['Part #', 'Capacity (tons)', 'Flange Range (in)', 'Weight (lbs)'],
    specRows: [
      ['PT-100',  '1',  '2.8 – 9',  '18'],
      ['PT-200',  '2',  '2.8 – 9',  '28'],
      ['PT-300',  '3',  '3.3 – 9',  '40'],
      ['PT-500',  '5',  '3.5 – 12', '66'],
      ['PT-1000', '10', '4.3 – 12', '132'],
    ],
    related: ['beam-clamp', 'chain-block'],
    tags: ['trolley', 'overhead'],
  },


  // ────────── WIRE ROPE SLINGS (new 2026) ──────────
  {
    id: 'wire-rope-sling-1leg',
    refPage: 'ref_wire_rope_sling_1leg',
    name: 'Standard Eye & Eye Wire Rope Sling',
    category: 'synthetic-slings',
    subcategory: 'Wire Rope Slings',
    page: 3,
    subtitle: '6 x 19 IWRC, EIPS · Vertical, Choker & Basket Hitches',
    standards: ['ASME B30.9'],
    material: '6x19 IWRC EIPS',
    finish: 'Bright or Galvanized',
    wllRange: '1,120 – 26,200 lbs (vertical)',
    designFactor: '5:1',
    description: '6x19 IWRC EIPS wire rope slings with mechanical splice eyes. Each sling proof tested to 2x WLL with certificate. Tagged with WLL, length, and serial number per OSHA 1910.184.',
    features: ['6x19 IWRC EIPS construction','Mechanical splice — proof tested 2× WLL','Domestic & import options','Multiple eye styles available','Cut-to-length available'],
    warnings: ['Inspect before each use. Reduce capacity for angle loading per ASME B30.9.'],
    related: ['wire-rope-sling-2leg','wire-rope-sling-choker','endless-roundslings'],
    tags: ['wire rope sling','eye and eye','overhead lifting'],
  },
  {
    id: 'wire-rope-sling-2leg',
    refPage: 'ref_wire_rope_sling_2leg',
    name: '2-Leg Bridle Wire Rope Sling',
    category: 'synthetic-slings',
    subcategory: 'Wire Rope Slings',
    page: 4,
    subtitle: '6 x 19 IWRC, EIPS · Eye & Eye Legs · Master Link + Hooks',
    standards: ['ASME B30.9'],
    material: '6x19 IWRC EIPS + Alloy Hardware',
    finish: 'Bright Rope, Painted Hardware',
    wllRange: 'Rated by angle (60° and 45°)',
    designFactor: '5:1',
    description: '2-leg wire rope bridle slings with forged alloy master link and hooks. Tagged with WLL at multiple angles.',
    features: ['2 eye-and-eye legs with master link','Forged alloy master link & hooks','Proof tested 2× WLL','Tagged at multiple angles'],
    warnings: ['Always rate at the included angle. Sharp angles dramatically reduce capacity.'],
    related: ['wire-rope-sling-1leg','wire-rope-sling-3leg','wire-rope-sling-4leg'],
    tags: ['wire rope sling','bridle','2-leg'],
  },
  {
    id: 'wire-rope-sling-3leg',
    refPage: 'ref_wire_rope_sling_3leg',
    name: '3-Leg Bridle Wire Rope Sling',
    category: 'synthetic-slings',
    subcategory: 'Wire Rope Slings',
    page: 5,
    subtitle: '6 x 19 IWRC, EIPS · Eye & Eye Legs · Master Link + 3 Hooks',
    standards: ['ASME B30.9'],
    material: '6x19 IWRC EIPS + Alloy Hardware',
    finish: 'Bright Rope, Painted Hardware',
    wllRange: 'Rated by angle (60° and 45°)',
    designFactor: '5:1',
    description: '3-leg wire rope bridle slings with forged alloy master link and hooks for 3-point lifts.',
    features: ['3 eye-and-eye legs with master link','Forged alloy master link & hooks','Proof tested 2× WLL','Tagged at multiple angles'],
    warnings: ['Always rate at the included angle.'],
    related: ['wire-rope-sling-2leg','wire-rope-sling-4leg'],
    tags: ['wire rope sling','bridle','3-leg'],
  },
  {
    id: 'wire-rope-sling-4leg',
    refPage: 'ref_wire_rope_sling_4leg',
    name: '4-Leg Bridle Wire Rope Sling',
    category: 'synthetic-slings',
    subcategory: 'Wire Rope Slings',
    page: 6,
    subtitle: '6 x 19 IWRC, EIPS · Eye & Eye Legs · Master Link + 4 Hooks',
    standards: ['ASME B30.9'],
    material: '6x19 IWRC EIPS + Alloy Hardware',
    finish: 'Bright Rope, Painted Hardware',
    wllRange: 'Rated by angle (60° and 45°)',
    designFactor: '5:1',
    description: '4-leg wire rope bridle slings with forged alloy master link and hooks. Per ASME B30.9, ratings assume worst-loaded leg supports an equal share only when load center is directly under hook.',
    features: ['4 eye-and-eye legs with master link','Forged alloy master link & hooks','Proof tested 2× WLL','Tagged at multiple angles'],
    warnings: ['Per B30.9, only 3 of 4 legs are assumed to share load equally.'],
    related: ['wire-rope-sling-2leg','wire-rope-sling-3leg'],
    tags: ['wire rope sling','bridle','4-leg'],
  },
  {
    id: 'wire-rope-sling-choker',
    refPage: 'ref_wire_rope_sling_choker',
    name: 'Choker Wire Rope Sling',
    category: 'synthetic-slings',
    subcategory: 'Wire Rope Slings',
    page: 7,
    subtitle: '6 x 19 IWRC, EIPS · Eye-and-Loop · For Choker Hitches',
    standards: ['ASME B30.9'],
    material: '6x19 IWRC EIPS',
    finish: 'Bright or Galvanized',
    wllRange: '820 – 27,400 lbs (choker)',
    designFactor: '5:1',
    description: 'Eye-and-loop wire rope slings for choker hitches. Larger eye sized for rope to pass through; smaller eye attaches to the hook.',
    features: ['Eye-and-loop mechanical splice','Proof tested 2× WLL','Sized eyes for clean choker bend','Custom lengths available'],
    warnings: ['Choker hitch reduces capacity to ~73% of vertical.'],
    related: ['wire-rope-sling-1leg','wire-rope-sling-2leg'],
    tags: ['wire rope sling','choker','eye and loop'],
  },

  // ────────── CABLE & WIRE ROPE (new 2026) ──────────
  {
    id: 'cable-7x19-galv',
    refPage: 'ref_cable_7x19_galv',
    name: '7x19 Galvanized Aircraft Cable',
    category: 'wire-rope',
    subcategory: 'Aircraft Cable',
    page: 14,
    subtitle: 'Galvanized Steel · Federal Spec RR-W-410, Type VI, Class 3',
    standards: ['Federal Spec RR-W-410','ASTM A1023'],
    material: 'Galvanized Steel',
    finish: 'Zinc Galvanized',
    wllRange: '1,000 – 14,400 lbs (MBS)',
    description: '7x19 construction galvanized aircraft cable. Zinc coating per ASTM A1023 for corrosion protection. Commercial grade — NOT for aircraft use.',
    features: ['Galvanized zinc coating','7x19 construction for max flexibility','Meets Federal Spec RR-W-410','Cut-to-length available','MIL-Spec & domestic available'],
    warnings: ['Never use at breaking strength. 10:1 safety factor minimum recommended.'],
    related: ['cable-7x19-galv-vinyl','cable-7x19-ss302','cable-7x19-ss316'],
    tags: ['aircraft cable','galvanized','7x19'],
  },
  {
    id: 'cable-7x19-galv-vinyl',
    refPage: 'ref_cable_7x19_galv_vinyl',
    name: '7x19 Galvanized Vinyl Coated Cable',
    category: 'wire-rope',
    subcategory: 'Vinyl Coated Cable',
    page: 17,
    subtitle: 'Vinyl Coated · 7x19 Construction · Galvanized Steel',
    standards: [],
    material: 'Galvanized Steel Core, PVC Jacket',
    finish: 'PVC Vinyl Coated',
    wllRange: '1,000 – 14,400 lbs (MBS)',
    description: 'Vinyl jacket over flexible 7x19 galvanized steel core. Custom colors available.',
    features: ['PVC vinyl coating','Non-marring surface','Galvanized steel core','Multiple OD options','Custom colors available'],
    warnings: ['Never use at breaking strength. Do not use for overhead lifting.'],
    related: ['cable-7x19-galv','cable-7x7-ss-vinyl','cable-7x19-ss-vinyl'],
    tags: ['aircraft cable','vinyl coated','7x19'],
  },
  {
    id: 'cable-7x19-ss302',
    refPage: 'ref_cable_7x19_ss302',
    name: '7x19 Stainless Aircraft Cable T302/304',
    category: 'wire-rope',
    subcategory: 'Aircraft Cable',
    page: 12,
    subtitle: 'Type 302/304 · Federal Spec RR-W-410, Type VI, Class 3',
    standards: ['Federal Spec RR-W-410'],
    material: 'Type 302/304 Stainless Steel',
    finish: 'Bright Stainless',
    wllRange: '270 – 12,000 lbs (MBS)',
    description: 'Type 302/304 stainless steel 7x19 aircraft cable with excellent corrosion resistance.',
    features: ['Type 302/304 stainless','7x19 max flexibility','Meets RR-W-410','Diameters 3/64" to 3/8"'],
    warnings: ['Never use at breaking strength.'],
    related: ['cable-7x19-ss316','cable-7x19-galv'],
    tags: ['stainless','aircraft cable','7x19','302','304'],
  },
  {
    id: 'cable-7x19-ss316',
    refPage: 'ref_cable_7x19_ss316',
    name: '7x19 Stainless Aircraft Cable T316',
    category: 'wire-rope',
    subcategory: 'Aircraft Cable',
    page: 13,
    subtitle: 'Type 316 · Marine Grade · Federal Spec RR-W-410',
    standards: ['Federal Spec RR-W-410'],
    material: 'Type 316 Stainless Steel',
    finish: 'Bright Stainless',
    wllRange: '335 – 10,680 lbs (MBS)',
    description: 'Type 316 stainless steel 7x19 aircraft cable. Maximum corrosion resistance — saltwater and chloride environments.',
    features: ['Type 316 max corrosion resistance','Marine grade','7x19 max flexibility','Meets RR-W-410'],
    warnings: ['Never use at breaking strength.'],
    related: ['cable-7x19-ss302','cable-7x19-ss-vinyl'],
    tags: ['stainless','aircraft cable','316','marine'],
  },
  {
    id: 'cable-7x7-ss-vinyl',
    refPage: 'ref_cable_7x7_ss_vinyl',
    name: '7x7 Stainless Vinyl Coated Cable',
    category: 'wire-rope',
    subcategory: 'Vinyl Coated Cable',
    page: 15,
    subtitle: 'PVC Coated · Type 304 & Type 316 · Commercial Grade',
    standards: [],
    material: 'SS 304/316 Core, PVC Jacket',
    finish: 'PVC Vinyl Coated',
    wllRange: '270 – 12,000 lbs (MBS)',
    description: 'PVC vinyl jacket over 7x7 stainless steel core. Available in SS 304 and SS 316.',
    features: ['PVC vinyl coating','SS 304 and SS 316 cores','Non-marring','Custom colors available'],
    warnings: ['Never use at breaking strength.'],
    related: ['cable-7x19-ss-vinyl','cable-7x19-galv-vinyl'],
    tags: ['stainless','vinyl coated','7x7'],
  },
  {
    id: 'cable-7x19-ss-vinyl',
    refPage: 'ref_cable_7x19_ss_vinyl',
    name: '7x19 Stainless Vinyl Coated Cable',
    category: 'wire-rope',
    subcategory: 'Vinyl Coated Cable',
    page: 16,
    subtitle: 'PVC Coated · 7x19 · Type 304 & Type 316',
    standards: [],
    material: 'SS 304/316 Core, PVC Jacket',
    finish: 'PVC Vinyl Coated',
    wllRange: '270 – 12,000 lbs (MBS)',
    description: 'PVC vinyl jacket over flexible 7x19 stainless steel core. Available in SS 304 and SS 316.',
    features: ['PVC vinyl coating','SS 304 and SS 316 cores','7x19 max flexibility','Custom colors available'],
    warnings: ['Never use at breaking strength.'],
    related: ['cable-7x7-ss-vinyl','cable-7x19-ss316'],
    tags: ['stainless','vinyl coated','7x19'],
  },

  // ────────── WEB SLING SHACKLES (new 2026) ──────────
  {
    id: 'shackle-web-sling',
    refPage: 'ref_shackle_web_sling',
    name: 'CM Web Sling Shackle',
    category: 'rigging-hardware',
    subcategory: 'Shackles',
    page: 19,
    subtitle: 'Carbon & Alloy Options · For Web & Round Sling Connections',
    standards: [],
    material: 'Carbon or Alloy Steel',
    finish: 'Hot Dip Galvanized',
    wllRange: '8,000 – 23,500 lbs (Carbon); 13,500 – 22,500 lbs (Alloy)',
    designFactor: '4:1 (Carbon), 6:1 (Alloy)',
    description: 'Web sling shackles designed to connect synthetic web and round slings to lifting hardware. Wide flat bearing surface protects sling from concentrated wear.',
    features: ['Carbon: 4:1 DF · Alloy: 6:1 DF','For 2"–6" wide web/round slings','Hot-dip galvanized','Wide pin protects sling','Zinc-plated linch pin standard'],
    warnings: ['Do not point load.'],
    related: ['shackles-anchor','endless-roundslings','eye-eye-web-slings'],
    tags: ['shackle','web sling','round sling'],
  },

  // ────────── HOISTS & TROLLEYS (new 2026) ──────────
  {
    id: 'badger-lever-hoist',
    refPage: 'ref_badger_lever_hoist',
    name: 'Badger Lever Chain Hoist — LC Series',
    category: 'lifting-equipment',
    subcategory: 'Lever Hoists',
    page: 29,
    subtitle: '3/4 to 6 Metric Ton · Zinc Plated Chain · 5, 10 & 20 ft. Lifts',
    standards: ['ASME B30.21','OSHA','NASA-STD-8719.9'],
    material: 'Forged Alloy Body · G80 Chain',
    finish: 'Painted',
    wllRange: '0.75 – 6 metric tons (1,650 – 13,200 lbs)',
    designFactor: '5:1',
    description: 'Badger LC Series lever chain hoists by AMH. Easy one-hand operation; free chain mode; non-slip rubber grip lever with 360° rotation. Fully enclosed horseshoe chain guard. Each hoist proof tested 1.25× WLL with test certificate.',
    features: ['Easy one-hand operation & free chain mode','Non-slip rubber grip lever, 360° rotation','20–30% less pull force than competitors','Fully enclosed horseshoe chain guard','Weston-style mechanical load brake','Drop forged alloy hooks with safety latch','G80 precision load chain, zinc plated','Proof tested 1.25× WLL with certificate','Shipyard hook option (1.5t & 3t)'],
    warnings: ['Never exceed capacity. Do not lift people or loads over people.'],
    related: ['lever-hoist','chain-block','beam-clamp','ya-lever-hoist'],
    tags: ['lever hoist','badger','LC series','overhead lifting'],
  },

  {
    id: 'ya-lever-hoist',
    refPage: 'ref_ya_lever_hoist',
    name: 'YA Lever Hoist',
    category: 'lifting-equipment',
    subcategory: 'Lever Hoists',
    page: 35,
    subtitle: '0.8 – 12 Metric Ton · 5 ft Standard Lift · Grade 105 / DIN 5684 Load Chain · Made in Japan',
    standards: ['DIN 5684'],
    material: 'Grade 105 Alloy Load Chain · Hardened Steel Body',
    finish: 'Electro-Deposited Black',
    wllRange: '0.8 – 12 metric tons (1,760 – 26,400 lbs)',
    designFactor: '4.2:1 – 6.5:1 (see safety factor by size)',
    description: 'Compact lever chain hoist for shop, jobsite, and shipyard lifting and pulling. Single-action free-spool releases the chain for quick load engagement; automatic load brake holds securely the moment the lever stops. All seven sizes share Grade 105 / DIN 5684 load chain, tip-supporting safety latches on both hooks, and an electro-deposited corrosion-resistant finish. Operates reliably from −20 to +130 °C (−4 to +266 °F). Test load is 150% of rated load.',
    features: ['Rounded lever — smooth pull against flat surfaces','Grade 105 load chain, DIN 5684 compliant','Single-action free-spool with automatic load brake','Tip-supporting safety latch on both hooks','Electro-deposited black finish on hoist body','Hardened steel bushings on side plates','Ratchet recovery: 16.5° (0.8–1 t) / 14° (1.6–12 t)','Nickel-plated disc hub & ratchet wheel','Operating range: −20 to +130 °C (−4 to +266 °F)'],
    warnings: ['Test load is 150% of rated WLL. Never exceed rated capacity.','Do not use for lifting people or loads over people.'],
    related: ['badger-lever-hoist','lever-hoist','chain-block','beam-clamp'],
    tags: ['lever hoist','YA series','elephant','grade 105','DIN 5684','japan'],
  },


  // ────────── 2026 ADDITIONS — Lifting Points / Beam Clamps ──────────
  {
    id: 'vlbg-lifting-point',
    refPage: 'ref_vlbg_lifting_point',
    name: 'Boltable Lifting Points — VLBG-Plus / VLBG',
    category: 'rigging-hardware',
    subcategory: 'Hoist Rings',
    page: 33,
    subtitle: 'Metric Thread · 360° Swivel · 180° Pivot · WLL 0.63–20 t',
    standards: ['ASME B30.26', 'EU 2006/42/EC'],
    material: 'Alloy Steel, Forged & Heat Treated',
    finish: 'Painted',
    wllRange: '0.63 – 20 metric tons',
    designFactor: '5:1',
    description: 'VLBG-Plus and VLBG boltable lifting points provide full rated capacity at any sling angle. Bail rotates 360° and body pivots 180° under load. Available in fixed length (12 sizes M8–M48) and variable length (4 sizes). Each unit individually proof-tested to 2.5× WLL and serialized.',
    features: ['360° swivel under load','180° pivot range','Metric thread sizes M8 through M48','High-strength alloy steel — forged & heat treated','Individually fatigue rated & proof tested 2.5× WLL','VLBG offers variable bolt lengths'],
    warnings: ['Torque mounting bolt to manufacturer spec before use.','Inspect annually per ASME B30.26.'],
    related: ['swivel-hoist-rings','eye-bolts','bc-bcd-beam-clamp'],
    tags: ['hoist ring','lifting point','swivel','metric','boltable'],
  },
  {
    id: 'bc-bcd-beam-clamp',
    refPage: 'ref_bc_bcd_beam_clamp',
    name: 'Beam Clamps — BC / BCD Series',
    category: 'lifting-equipment',
    subcategory: 'Beam Clamps',
    page: 34,
    subtitle: '1 to 10 Metric Ton · BC Fixed · BCD Movable Shackle · Theatrical Black',
    standards: ['ASME B30', 'OSHA', 'NASA-STD-8719.9', 'EU 2006/42/EC'],
    material: 'Forged Steel',
    finish: '"Theatrical Black" Matte',
    wllRange: '1 – 10 metric tons',
    designFactor: '5:1',
    description: 'Beam clamps for powered or manual hoists. Simple hand installation — no tools required. Compact low-headroom design. BC model is fixed mount (vertical loading only); BCD model has a movable shackle rated for angular loading up to 45°. Theatrical Black matte finish.',
    features: ['No tools required — hand tightened','Compact low-headroom design','BC model: fixed mount, vertical only','BCD model: movable shackle, angular load rated','"Theatrical Black" matte finish','5:1 design factor','Serialized with test certificate'],
    warnings: ['Verify full-flange engagement before applying load.','Never exceed capacity.','BC model rated at 0° vertical only — use BCD for angular loads.'],
    related: ['beam-clamp','trolley','chain-block','vlbg-lifting-point'],
    tags: ['beam clamp','theatrical','low headroom','BC','BCD'],
  },

  // ────────── SLING PROTECTION ──────────
  {
    id: 'sling-edge-guards',
    name: 'Cornermax Sling Edge Guards',
    category: 'sling-protection',
    subcategory: 'Edge Protection',
    page: 70,
    subtitle: 'High Cut-Resistance · For Synthetic Slings',
    standards: ['CEN 15112'],
    material: 'Ultra-High-Molecular-Weight Polyethylene',
    finish: 'Yellow',
    wllRange: 'Matched to sling size',
    description: 'Cornermax corner protectors use high-cut-resistance material to protect synthetic slings from sharp edges. Dramatically extends sling life.',
    features: [
      'UHMW polyethylene construction',
      'Superior cut resistance vs. rubber or nylon pads',
      'Sized to sling width and body',
      'Reusable',
    ],
    warnings: [
      'Edge protection is required — not optional — any time a synthetic sling crosses a corner or edge.',
    ],
    specHeaders: ['Part #', 'Sling Width (in)', 'Length (in)'],
    specRows: [
      ['CMX-2',  '2',  '12'],
      ['CMX-3',  '3',  '12'],
      ['CMX-4',  '4',  '12'],
      ['CMX-6',  '6',  '18'],
      ['CMX-8',  '8',  '18'],
      ['CMX-10', '10', '24'],
    ],
    related: ['endless-roundslings', 'eye-eye-web-slings'],
    tags: ['edge protection', 'UHMW', 'corner'],
  },
];
